### PR TITLE
Adding the logged Exception-object as ExtendedProperty

### PR DESCRIPTION
**Pull request by burningice2866**
This Pull Request adds the logged Exception as a Extended Property to the LogEntry object written to the Logging Framework.

This enables custom Trace Listeners to later retrieve the Exception and use it like this

```
var entry = (LogEntry)data;
if (entry.ExtendedProperties.ContainsKey("Exception"))
{
   var exc = entry.ExtendedProperties["Exception"] as Exception;
   if (exc != null)
   {
      // Do something with exc
   }
}
```

Example of Code using this feature for correctly logging errors to Stackify https://github.com/burningice2866/CompositeC1Contrib/blob/master/Stackify/StackifyTraceListener.cs#L74

### CODE REVIEW

**Comment by kasravi** [comment]
it is a good feature to be added, some thoughts before looking further:
1. you have used the string key "Exception" several times, isn't it better to centralize it?
2. for getting the exception those lines should be rewritten, giving out an abstraction might be a better idea
3. there are numerous changes in spacing in the commit, if they are necessary they should be committed separately with their own message.

**Comment by burningice2866** [comment]
What are you referring to? The string "Exception" is only mentioned once https://github.com/Orckestra/CMS-Foundation/pull/178/files?w=1#diff-ddf50714934ec16d419f222be8077fd0R85

**Comment by kasravi** [comment]
I'm also referring to usage. in case anyone wants to use it, two times again. I'm saying it based on your sample usage code.

**Comment by burningice2866** [comment]
Why don't we try to keep focus on the actual pull request - how a random sample code is constructed is hardly relevant.

**Comment by mawtex** [comment]
@burningice2866 the use of ExtendedProperties["Exception"] - can you point to existing trace listeners that react to this or conventions on using this property to store an Exception? 

If not, then we are making a public log method taking an exception, which will send this exception object to /dev/null - unless a specific custom trace listener (reacting to this extended property) is attached. That might create some unneeded confusion.

How about having a "Dictionary<string,object> extendedProperties" argument instead and attach all entries as extended properties? This better indicate that you should have an intimate relationship with the trace listener for things to work. Then you can add { "Exception", exc } and see this flow to your listener.

**Comment by burningice2866** [comment]
@mawtex Naturally no existing trace listeners, except my own, which use this property since it doesn't exist yes. Chicken and Egg problem. [The first sample project on EntLib (Custom Exception Handler)](http://entlib.codeplex.com/wikipage?title=Sample%20Projects) uses exactly this approach though so its the recommended approach from Microsoft if you need to pass on your exception object.

The inherent design flaw in the way you use the logging library is that you serialize the exception to a string before any Listener got the chance to work with it. This should have been done in [FileLogTraceListener](https://github.com/Orckestra/CMS-Foundation/blob/dev/Composite/Plugins/Logging/LogTraceListeners/FileLogTraceListener/FileLogTraceListener.cs). In the current pattern there is no way to reconstruct the exception from string.

You're correct in pointing out that the new `static public void LogEntry(string, string, Exception, Category, TraceEventType, int, int) method` can cause some confusion ant i'll make it private instead, so that you can't log an Exception without calling any of the desired wrapper-methods which serializes it as a string first.

Regarding your last comment - ExtendedProperties is already a Dictionary<string,object> property of the [LogEntry](https://msdn.microsoft.com/en-us/library/microsoft.practices.enterpriselibrary.logging.logentry.extendedproperties.aspx) class so i'm, not sure i follow you there.

**Comment by burningice2866** [comment]
@kasravi Why hasn't this been merged into dev or vnext !? Do you need anything more from me?

**Comment by burningice2866** [comment]
@kasravi Why hasn't this been merged into dev or vnext !? Do you need anything more from me?

**Comment by mawtex** [comment]
@burningice2866 I have an issue with the fact that you introduce a public log method (line 94) that takes an Exception object as parameter, but this info is not used by the default logging provider we ship with. It would likely lead to some confusion, since other methods we have will do just this.

**Comment by burningice2866** [comment]
@mawtex what methods are you referring to? And how come you accept the pull request if you have outstanding issues?

**Comment by mawtex** [comment]
@burningice2866 we pulled into a branch to run a build on it. The issue is with this overload:

`static public void LogEntry(string title, string message, Exception exc, Category category, System.Diagnostics.TraceEventType severity, int priority)`

where the exc input ends up as an extended parameter, which is not handled by the logging providers as is.  For other overloads taking exceptions, it will be written to logs. The logging providers in the core isn't handling extended properties. Also I'm guessing that using other EntLib loggers may not document the exception either (I didn't dive that deep though).

Sorry for not getting back to you earlier.

Perhaps a fix would be to ensure the API is being explicit about info passed as an extended property, so the consumer of the API fully understand that specific loggers is needed to capture the exception passed (or ensure the message for this particular overload include the exception).

**Comment by burningice2866** [comment]
@mawtex i reopened a new PR which doesn't change the API surface here https://github.com/Orckestra/CMS-Foundation/pull/363

**Pull request merged**
